version: '3.7'
services:

# -----------------------------------------------------------------
  monero_mining:
    build:
      dockerfile: Dockerfile
      context: ./
  
    container_name: monero_mining
    image: monero_mining:1.0.0
    restart: unless-stopped  
    
    command: tail -F anything && chmod a+x /src/start.sh

    #command: cd xmrig/build && ./xmrig

    volumes:
      - ./config.json:/src/xmrig/build/config.json:ro
      - ./cron.d:/etc/cron.d
      - ./start.sh:/src/start.sh